// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerRanking.Data;

namespace PlayerRanking.Migrations
{
    [DbContext(typeof(AtpContext))]
    partial class AtpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("PlayerRanking.Models.FavoritePlayer", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AgeAtRankDate")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTie")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LastWeekPosMove")
                        .HasColumnType("int");

                    b.Property<string>("NatlId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbrEventsPlayed")
                        .HasColumnType("int");

                    b.Property<int>("NextBestPoints")
                        .HasColumnType("int");

                    b.Property<string>("PlayerGladiatorImageCmsUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerHeadshotImageCmsUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("PointsDropping")
                        .HasColumnType("int");

                    b.Property<int>("PrevPoints")
                        .HasColumnType("int");

                    b.Property<int>("PrevRank")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerId");

                    b.ToTable("FavoritePlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
